-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE ADMINISTRADOR (
ID_ADM INT(5) PRIMARY KEY AUTO_INCREMENT,
NOME_ADM VARCHAR(100) NOT NULL,
SOBRENOME_ADM VARCHAR(150) NOT NULL,
USUARIO_ADM VARCHAR(200) NOT NULL,
SENHA_ADM VARCHAR(200) NOT NULL,
IMAGEM_ADM LONGBLOB NULL
);

CREATE TABLE REL (
ID_REL INT(5) PRIMARY KEY AUTO_INCREMENT,
FK_FUNCIONARIO INT(5),
FK_ORDEM INT(5),
FK_HISTORICO INT(5)
);

CREATE TABLE FUNCIONARIOS (
ID_FUNCIONARIO INT(5) PRIMARY KEY AUTO_INCREMENT,
NOME_FUNCIONARIO VARCHAR(100) NOT NULL,
SOBRENOME_FUNCIONARIO VARCHAR(200) NOT NULL,
USUARIO_FUNCIONARIO VARCHAR(200) NULL,
SENHA_FUNCIONARIO VARCHAR(250) NULL,
IMAGEM_FUNCIONARIO LONGBLOB NULL,
STATUS_FUNCIONARIO ENUM('ATIVO','INATIVO')
);

CREATE TABLE RELATORIO_FUNCIONARIOS (
ID_RELATORIO INT(5) PRIMARY KEY AUTO_INCREMENT,
FK_FUNCIONARIO INT(5),
DATA_ATUALIZACAO DATETIME NULL,
ORDENS_ATENDIDAS INT(5) NULL,
ORDENS_ABERTAS INT(5) NULL,
ORDENS_CONCLUIDA VARCHAR(10) NULL,
ORDENS_CANCELADAS VARCHAR(10) NULL,
FOREIGN KEY(FK_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO)
);

CREATE TABLE HISTORICO_ORDEM (
ID_HISTORICO INT(5) PRIMARY KEY AUTO_INCREMENT,
DATA_FINALIZACAO DATETIME NULL,
TEMPO_ATENDIMENTO DATETIME NULL,
NOTAS VARCHAR(500) NULL,
DATA_EXECUCAO VARCHAR(10) NULL
);

CREATE TABLE ORDEM (
ID_ORDEM INT(5) PRIMARY KEY AUTO_INCREMENT,
SERVICO VARCHAR(200),
ITEM VARCHAR(200),
LOCALIZACAO VARCHAR(200),
PRAZO DATETIME,
PRIORIDADE VARCHAR(200),
STATUS ENUM('PENDENTE','EM ANDAMENTO','CONCLUIDO','CANCELADO'),
NUMERO_OS VARCHAR(10),
FOTO VARCHAR(400),
CRIADO DATETIME
);

CREATE TABLE ALTERACAO_ORDEM (
ID_AO INT(5) PRIMARY KEY AUTO_INCREMENT,
DATA_ALTERACAO DATETIME,
CAMPO_ALTERACAO ENUM('SERVICO','ITEM','LOCALIZACAO','PRAZO','PRIORIDADE','STATUS','NUMERO_OS','FOTO'),
ALTERACAO VARCHAR(300),
FK_ORDEM INT(5)
);

ALTER TABLE ALTERACAO_ORDEM ADD FOREIGN KEY(FK_ORDEM) REFERENCES ORDEM (ID_ORDEM);
ALTER TABLE REL ADD FOREIGN KEY(FK_FUNCIONARIO) REFERENCES FUNCIONARIOS (ID_FUNCIONARIO);
ALTER TABLE REL ADD FOREIGN KEY(FK_ORDEM) REFERENCES ORDEM (ID_ORDEM);
ALTER TABLE REL ADD FOREIGN KEY(FK_HISTORICO) REFERENCES HISTORICO_ORDEM (ID_HISTORICO)
